
-- 9번 질문 - row개수가 안맞는데 잘못 푼건지? 
-- 12번 질문 
-- 13번 
-- 14번 

SELECT *
FROM TB_STUDENT;

SELECT *
FROM TB_GRADE;

SELECT *
FROM TB_DEPARTMENT;

SELECT STUDENT_NAME, STUDENT_NO
FROM TB_STUDENT
    JOIN TB_GRADE USING(STUDENT_NO)
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' 
    AND SUM(POINT) 
GROUP BY STUDENT_NAME, STUDENT_NO;

SELECT STUDENT_NO,SUM(POINT)
FROM TB_GRADE G
    JOIN TB_STUDENT S
HAVING SUM(POINT) >= ALL(SELECT SUM(POINT) FROM TB_GRADE WHERE G.STUDENT_NO = S.STUDENT_NO);


-- [Additional SELECT - Option]




-- 1. 
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1;





-- 2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

SELECT *
FROM TB_STUDENT
ORDER BY STUDENT_ADDRESS;

SELECT *
FROM ;




-- 3. 
SELECT STUDENT_NAME AS 학생이름, STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1, 2) IN ('강원', '경기'); AND TO_NUMBER(SUBSTR(STUDENT_NO, 1, 2)) BETWEEN 90 AND 99;




--4. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_NAME DESC;

SELECT *
FROM TB_PROFESSOR;




-- 5. 
SELECT STUDENT_NO, TO_CHAR(POINT, '9.00')
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC;

SELECT *
FROM TB_GRADE;




-- 6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;

SELECT *
FROM TB_STUDENT;




-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);
   
   
   
    
-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
    JOIN TB_PROFESSOR USING(PROFESSOR_NO);
 
 
 
    
-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

SELECT *
FROM TB_CLASS;

SELECT *
FROM TB_CLASS_PROFESSOR;

SELECT *
FROM TB_PROFESSOR;

SELECT *
FROM TB_DEPARTMENT;




-- 10
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT), 1)
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;




--11
-- 처음 푼 
SELECT DEPARTMENT_NAME, STUDENT_NAME, COACH_PROFESSOR_NO
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

-- 다시 푼 
SELECT DISTINCT(DEPARTMENT_NAME) AS 학과이름, 
        STUDENT_NAME AS 학생이름, 
        (SELECT PROFESSOR_NAME FROM TB_PROFESSOR JOIN TB_STUDENT ON COACH_PROFESSOR_NO = PROFESSOR_NO WHERE STUDENT_NO = 'A313047') AS 지도교수이름
FROM TB_STUDENT 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR  USING(DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

SELECT *
FROM TB_PROFESSOR;





-- 12
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
    JOIN TB_CLASS USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND SUBSTR(TERM_NO, 1, 4) = '2007'
GROUP BY STUDENT_NAME, TERM_NO
ORDER BY 1;

SELECT *
FROM TB_GRADE;

SELECT *
FROM TB_DEPARTMENT
ORDER BY DEPARTMENT_NAME;






-- 13
SELECT CLASS_NAME, DEPARTMENT_NAME, CLASS_NO, PROFESSOR_NO
FROM TB_CLASS 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE CATEGORY = '예체능';

SELECT *
FROM TB_CLASS;

SELECT *
FROM TB_CLASS_PROFESSOR;

SELECT *
FROM TB_DEPARTMENT 
    LEFT JOIN TB_CLASS USING(DEPARTMENT_NO)
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO);

-- 총 882 / 776 





-- 14

SELECT *
FROM TB_STUDENT;

SELECT STUDENT_NAME
FROM TB_STUDENT S
    JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
    JOIN TB_PROFESSOR P ON D.DEPARTMENT_NO = P.DEPARTMENT_NO
WHERE D.DEPARTMENT_NAME = '서반아어학과';

SELECT STUDENT_NAME, COACH_PROFESSOR_NO
FROM TB_STUDENT S
    JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE D.DEPARTMENT_NAME = '서반아어학과';

SELECT STUDENT_NAME, COACH_PROFESSOR_NO
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';

SELECT STUDENT_NAME, (SELECT PROFESSOR_NAME FROM TB_PROFESSOR P
                                                JOIN TB_STUDENT ON COACH_PROFESSOR_NO = P.PROFESSOR_NO 
                                                JOIN TB_DEPARTMENT D ON P.DEPARTMENT_NO = D.DEPARTMENT_NO
                                            WHERE D.DEPARTMENT_NAME = '서반아어학과')
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과';





--15
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, TRUNC( AVG(POINT), 5)
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;





-- 16
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT), 8)
FROM TB_CLASS
    JOIN TB_GRADE USING(CLASS_NO)
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE = '
GROUP BY CLASS_NO, CLASS_NAME;














