SELECT LENGTH('select')
FROM DUAL;

SELECT EMP_NAME, LENGTH(EMP_NAME), EMAIL
FROM EMPLOYEE;

SELECT EMP_NAME, EMAIL, LENGTH(EMAIL)
FROM EMPLOYEE
WHERE LENGTH(EMAIL) < 16;

SELECT EMP_NAME, EMAIL, LENGTHB(EMP_NAME), LENGTHB(EMAIL)
FROM EMPLOYEE;

SELECT INSTR('KOREA', 'R')
FROM DUAL;

SELECT INSTR('KOREA KOREA', 'R', 4)
FROM DUAL;

SELECT INSTR('KOREA KOREA', 'R', -1, 1)
FROM DUAL;

SELECT EMAIL, INSTR(EMAIL, '@')
FROM EMPLOYEE;

SELECT LPAD('KOREA', 10)
FROM DUAL;

SELECT RPAD('KOREA', 10)
FROM DUAL;

SELECT LPAD('KOREA', 10, '*')
FROM DUAL;

SELECT EMP_NAME, RPAD(EMAIL, 18, '*')
FROM EMPLOYEE;

SELECT LTRIM('    KOREA    ')
FROM DUAL;

SELECT LTRIM('000000123450000', '0')
FROM DUAL;

SELECT LTRIM('0123455KOREA', '0123455')
FROM DUAL;

SELECT LTRIM(RTRIM('234432493487YEJIN4834927827', '4834927827'), '234432493487')
FROM DUAL;

SELECT TRIM('    KOREA    ') AS A
FROM DUAL;

SELECT TRIM('   DFSD  FSDF  SDF DSF  ') AS A
FROM DUAL;

SELECT TRIM('D' FROM 'DFSD  FSDF  SDF DSF  ') AS A
FROM DUAL;

SELECT TRIM(LEADING 'Z' FROM 'ZZZZKORZEAZZZZ') AS A
FROM DUAL;

SELECT SUBSTR('KOREAAAKOREAKK', 8)
FROM DUAL;

SELECT SUBSTR('KOREAAAKOREAKK', 8, 2)
FROM DUAL;

SELECT SUBSTR('1OREAAAKOREAKK', -2, 2)
FROM DUAL;

SELECT EMP_NAME, SUBSTR(EMP_NO, 1, 6) 
FROM EMPLOYEE;

SELECT LOWER('FSDFWE')
FROM DUAL;

SELECT UPPER('sdfs')
FROM DUAL;

SELECT INITCAP('sdfFdsfFSDF')
FROM DUAL;

SELECT EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '%a%';

SELECT EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '%A%';

SELECT EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE LOWER('%A%');

SELECT CONCAT('AAA', 'GGG')
FROM DUAL;

SELECT 'AAA'|| 'GGG'
FROM DUAL;

SELECT CONCAT(EMP_NAME, '님')
FROM EMPLOYEE;

SELECT REPLACE('KKOREA', 'K', 'Z')
FROM DUAL;

SELECT REVERSE('ABC')
FROM DUAL;

SELECT TRANSLATE('04235', '0123456789', '영일이삼사오육칠팔구')
FROM DUAL;

SELECT EMP_NAME, EMP_NO, REVERSE(EMP_NO)
FROM EMPLOYEE;

SELECT ABS(10), ABS(-10)
FROM DUAL;

SELECT MOD(100, 3)
FROM DUAL;

SELECT MOD(SALARY, 3)
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE MOD(SALARY, 3) = 0; 

SELECT ROUND(123.123), ROUND(123.789)
FROM DUAL;

SELECT ROUND(123.567, -2)
FROM DUAL;

SELECT FLOOR(123.999)
FROM DUAL;

SELECT TRUNC(123.999)
FROM DUAL;

SELECT TRUNC(123.999, 2)
FROM DUAL;

SELECT CEIL(123.123)
FROM DUAL;

SELECT EMP_NAME, FLOOR(SALARY+(SALARY * BONUS) / 3)
FROM EMPLOYEE;

SELECT SYSDATE
FROM DUAL;

SELECT SYSDATE, CURRENT_DATE
FROM DUAL;

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL;

SELECT SYSDATE-1 AS 어제, SYSDATE AS 오늘, SYSDATE+1 AS 내일
FROM DUAL;

SELECT SYSDATE - TO_DATE('01-01-24', 'YY-MM-DD')
FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 5)
FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 18) AS 전역일
FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('21/01/01', 'RR/MM/DD'))
FROM DUAL;

SELECT SYSDATE, NEXT_DAY(SYSDATE, '월')
FROM DUAL;

SELECT LAST_DAY(SYSDATE)
FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE)
FROM DUAL;

SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000;



