
SELECT SUBSTR('오라클 데이터베이스', 4, 6)
FROM DUAL;

SELECT LPAD('ORACLE', 10, '+')
FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, '20/01/01')
FROM DUAL;

SELECT COUNT(*), COUNT(EMP_NO), COUNT(MANAGER_ID)
FROM EMPLOYEE;

SHOW ERRORS;